server {
    listen 80;
    server_name bot.weupbook.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name bot.weupbook.com;

    ssl_certificate     /etc/letsencrypt/live/bot.weupbook.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bot.weupbook.com/privkey.pem;

    location / {
        proxy_pass         http://app:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 310s;
    }
}
